# Generated by Django 2.1.1 on 2018-09-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_client_levels_partner_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_levels',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='partner_levels',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='skill_levels',
            old_name='name',
            new_name='value',
        ),
    ]
