# Generated by Django 2.1.1 on 2018-09-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180918_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_levels',
            options={'verbose_name_plural': 'client_levels'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='partner_levels',
            options={'verbose_name_plural': 'partner_levels'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='skill_levels',
            options={'verbose_name_plural': 'skill_levels'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'skills'},
        ),
    ]
