# Generated by Django 2.1.1 on 2018-09-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assoc_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'assoc_availabilities',
            },
        ),
        migrations.CreateModel(
            name='assoc_client_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'assoc_client_relationships',
            },
        ),
        migrations.CreateModel(
            name='assoc_partner_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'assoc_partner_relationships',
            },
        ),
        migrations.CreateModel(
            name='assoc_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'assoc_skills',
            },
        ),
        migrations.CreateModel(
            name='associate_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rate', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.locations')),
            ],
            options={
                'verbose_name_plural': 'associate_table',
            },
        ),
        migrations.AddField(
            model_name='assoc_skills',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associates.associate_table'),
        ),
        migrations.AddField(
            model_name='assoc_skills',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.skill_levels'),
        ),
        migrations.AddField(
            model_name='assoc_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.skills'),
        ),
        migrations.AddField(
            model_name='assoc_partner_relationship',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associates.associate_table'),
        ),
        migrations.AddField(
            model_name='assoc_partner_relationship',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.partner_levels'),
        ),
        migrations.AddField(
            model_name='assoc_partner_relationship',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.partners'),
        ),
        migrations.AddField(
            model_name='assoc_client_relationship',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associates.associate_table'),
        ),
        migrations.AddField(
            model_name='assoc_client_relationship',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.clients'),
        ),
        migrations.AddField(
            model_name='assoc_client_relationship',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.client_levels'),
        ),
        migrations.AddField(
            model_name='assoc_availability',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associates.associate_table'),
        ),
        migrations.AddField(
            model_name='assoc_availability',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.availability_levels'),
        ),
        migrations.AddField(
            model_name='assoc_availability',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.weeks'),
        ),
        migrations.AlterUniqueTogether(
            name='assoc_skills',
            unique_together={('associate_id', 'skill_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assoc_partner_relationship',
            unique_together={('associate_id', 'partner_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assoc_client_relationship',
            unique_together={('associate_id', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='assoc_availability',
            unique_together={('associate_id', 'week_id')},
        ),
    ]
