# Generated by Django 2.1.1 on 2018-09-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proj_associates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='associates.associate_table')),
            ],
            options={
                'verbose_name_plural': 'proj_associates',
            },
        ),
        migrations.CreateModel(
            name='proj_client_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMin', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.clients')),
                ('minimum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.client_levels')),
            ],
            options={
                'verbose_name_plural': 'proj_client_relationships',
            },
        ),
        migrations.CreateModel(
            name='proj_partner_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMin', models.BooleanField(default=False)),
                ('minimum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.partner_levels')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.partners')),
            ],
            options={
                'verbose_name_plural': 'proj_partner_relationship',
            },
        ),
        migrations.CreateModel(
            name='proj_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMin', models.BooleanField(default=False)),
                ('minimum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.skill_levels')),
            ],
            options={
                'verbose_name_plural': 'proj_skills',
            },
        ),
        migrations.CreateModel(
            name='proj_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.locations')),
            ],
            options={
                'verbose_name_plural': 'project_table',
            },
        ),
        migrations.AddField(
            model_name='proj_skills',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proj_table'),
        ),
        migrations.AddField(
            model_name='proj_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.skills'),
        ),
        migrations.AddField(
            model_name='proj_partner_relationship',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proj_table'),
        ),
        migrations.AddField(
            model_name='proj_client_relationship',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proj_table'),
        ),
        migrations.AddField(
            model_name='proj_associates',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.proj_table'),
        ),
        migrations.AlterUniqueTogether(
            name='proj_skills',
            unique_together={('project_id', 'skill_id')},
        ),
        migrations.AlterUniqueTogether(
            name='proj_partner_relationship',
            unique_together={('project_id', 'partner_id')},
        ),
        migrations.AlterUniqueTogether(
            name='proj_client_relationship',
            unique_together={('project_id', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='proj_associates',
            unique_together={('project_id', 'associate_id')},
        ),
    ]
