# Generated by Django 2.1.1 on 2018-10-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_table',
            name='team_size',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proj_associates',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associates.associate_table'),
        ),
        migrations.AlterField(
            model_name='proj_associates',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proj_table'),
        ),
        migrations.AlterField(
            model_name='proj_client_relationship',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.clients'),
        ),
        migrations.AlterField(
            model_name='proj_client_relationship',
            name='minimum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.client_levels'),
        ),
        migrations.AlterField(
            model_name='proj_client_relationship',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proj_table'),
        ),
        migrations.AlterField(
            model_name='proj_partner_relationship',
            name='minimum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.partner_levels'),
        ),
        migrations.AlterField(
            model_name='proj_partner_relationship',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.partners'),
        ),
        migrations.AlterField(
            model_name='proj_partner_relationship',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proj_table'),
        ),
        migrations.AlterField(
            model_name='proj_skills',
            name='minimum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.skill_levels'),
        ),
        migrations.AlterField(
            model_name='proj_skills',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proj_table'),
        ),
        migrations.AlterField(
            model_name='proj_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.skills'),
        ),
    ]
